-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.16.0-integration-engines-4-16-0-63-integration-tracing-runtime-js-9f7de8712f7653c6264679213b3c779d11e2dc28.1"]
    minimum_pre_commit_version: '0'
