-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.7.0-integration-engines-4-7-0-17-integration-closed-itx-error-message-279c624b671dee4a1785e2f8597626b4bbe06083.1"]
    minimum_pre_commit_version: '0'
