-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.4.0-integration-engines-4-4-0-56-integration-sqlite-conversion-panic-3ba0d959e76c2282691aecac535009a8c0fd2ff1.1"]
    minimum_pre_commit_version: '0'
