-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.7.0-integration-engines-4-7-0-20-integration-closed-itx-error-message-a07aa517fd2298a2f12569fb2e07a1fd1f40879c.1"]
    minimum_pre_commit_version: '0'
