-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.3.0-integration-engines-4-3-0-23-integration-tracing-high-res-time-727d86ca4ace27b862718bf9064f1f82269912c1.1"]
    minimum_pre_commit_version: '0'
