-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.4.0-integration-engines-4-4-0-45-mongodb-url-error-038539e4f3ccddf32d7f3eaa63da07b1f3db2386.1"]
    minimum_pre_commit_version: '0'
