-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@2.29.0-integration-buildkite-move-folder.1"]
    minimum_pre_commit_version: '0'
