-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.14.0-integration-engines-4-14-0-25-integration-warning-rendering-in-rust-1cf4f0a23c0f00aa9a916cce0695c6f4606ffefb.1"]
    minimum_pre_commit_version: '0'
