-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.3.0-integration-engines-4-3-0-25-qe-multi-schema-eb81cea0c7c7c3624102ebb6bcba12b8b8a602cc.1"]
    minimum_pre_commit_version: '0'
