-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.8.0-integration-engines-4-8-0-26-integration-introspect-composite-type-depth-to-isize-781dae0383e8814e59be42664dec396895230342.1"]
    minimum_pre_commit_version: '0'
