-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.10.0-integration-engines-4-10-0-22-integration-log-capture-ff36a734959e118dc6a09f2578bb31abda72e76e.1"]
    minimum_pre_commit_version: '0'
