-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.5.0-integration-engines-4-5-0-4-integration-referential-integrity-to-relation-mode-036fe8cea132c9f376eb7648e202485b6a5287dc.1"]
    minimum_pre_commit_version: '0'
