-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.12.0-integration-engines-4-12-0-11-integration-tech-spans-e8ae892390e8c056c72f885f76f3999e3c81e154.1"]
    minimum_pre_commit_version: '0'
