-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.4.0-integration-engines-4-4-0-39-integration-query-raw-itx-mongo-a52d215fb2b3cba53b195bbf56b09fc615ddad3d.1"]
    minimum_pre_commit_version: '0'
