-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.5.0-integration-engines-4-5-0-5-integration-referential-integrity-to-relation-mode-03c061955daafa43d6cd07f0fc968ea3c723773c.1"]
    minimum_pre_commit_version: '0'
