-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.17.0-integration-engines-4-17-0-3-integration-alula-ipv6-37e21ce44992c3c1449e7eaaca8c082507b653fb.1"]
    minimum_pre_commit_version: '0'
