-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@1.32.0-alpha.3"]
    minimum_pre_commit_version: '0'
