-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.1.0-integration-engines-5-1-0-12-integration-ipv6-with-tests-62ef4e5560580828e96e1cfe9557c4a0c4a33484.1"]
    minimum_pre_commit_version: '0'
