-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.12.0-integration-engines-4-12-0-36-integration-errors-jsonp-4acc7604137b1795f92ed92a36c6ab4d9f42430b.1"]
    minimum_pre_commit_version: '0'
