-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.7.0-integration-engines-5-7-0-29-integration-sql-nested-transactions2-e943433a36b16524e1d88f0f0b93c3d8d4ddd4c8.2"]
    minimum_pre_commit_version: '0'
