-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.10.0-integration-engines-4-10-0-80-integration-direct-url-fix-c46ccd25d43ebe3a797d38ff47c6a3cc6913ef79.1"]
    minimum_pre_commit_version: '0'
