-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.7.0-integration-engines-4-7-0-12-integration-set-napi-to-2-9-1-3672cb64a55825e65c2a43eff3142646f4341f59.1"]
    minimum_pre_commit_version: '0'
