-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@3.13.0-integration-remove-preview-from-migrate-diff-and-db-execute.1"]
    minimum_pre_commit_version: '0'
