-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.7.0-integration-engines-4-7-0-37-integration-itx-remove-preview-feature-d49c60b9b24079055b2e8e17c3a449d4424c42f0.1"]
    minimum_pre_commit_version: '0'
