-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.15.0-integration-engines-4-15-0-25-integration-support-arrays-generator-config-c80941ed3b82adfa88fb04685878e290eb8b6620.1"]
    minimum_pre_commit_version: '0'
