-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.10.0-integration-engines-4-10-0-47-integration-log-capture-3aa0d7b5675f501f97951f338fcfc5078dde294e.1"]
    minimum_pre_commit_version: '0'
