-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.16.0-integration-engines-4-16-0-21-integration-node-drivers-typed-49c3279792632f97a8f9f76330445640a49dcec0.1"]
    minimum_pre_commit_version: '0'
