-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.14.0-integration-engines-4-14-0-35-integration-remove-napi-get-config-d0198acc2075abd35dfad75addd5a5975488c34b.1"]
    minimum_pre_commit_version: '0'
