-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.10.0-integration-engines-5-10-0-1-integration-minimal-qe-wasm-no-schema-df8fed62839069ce077de68f26b347159d4bb4ad.2"]
    minimum_pre_commit_version: '0'
