-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.12.0-integration-engines-4-12-0-20-integration-dmmf-relation-field-ordering-b48e25dea85b3d99a521f4619eda7982ec3aaf0a.1"]
    minimum_pre_commit_version: '0'
