-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.8.0-integration-engines-5-8-0-8-integration-mongodb-2-8-0-f60e13569866f407fae88c54f36658b3fe1ab26a.1"]
    minimum_pre_commit_version: '0'
