-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.16.0-integration-engines-4-16-0-20-integration-improve-field-ref-validation-238ecf6c8d3482d7d27517872e056014a2742297.1"]
    minimum_pre_commit_version: '0'
