-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.5.0-integration-feat-deno-deploy.1"]
    minimum_pre_commit_version: '0'
