-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.16.0-integration-engines-4-16-0-19-integration-only-upload-to-all-commits-85e190cf5d4e54af3674e0367921657166a4b7e0.1"]
    minimum_pre_commit_version: '0'
