-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.14.0-integration-engines-4-14-0-59-integration-glibc-unification-21a75d2f920e675e6fe5d7f247ebbfbc8b6d24b3.1"]
    minimum_pre_commit_version: '0'
