-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.16.0-integration-engines-4-16-0-55-integration-node-drivers-naming-consistency-34882a922df80c18cdc4d8165413e6e5bfa92be2.1"]
    minimum_pre_commit_version: '0'
