-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.16.0-integration-engines-4-16-0-15-integration-node-drivers-c750faaec2e560cab1a3eeac4bf8e6cc17bf5b8c.1"]
    minimum_pre_commit_version: '0'
