-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.14.0-integration-engines-4-14-0-50-integration-windows-static-crt-9995f453ef123ca3299c0ae3332ea512d9cdd4bb.1"]
    minimum_pre_commit_version: '0'
