-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.17.0-integration-engines-4-17-0-23-integration-chore-update-data-proxy-error-d1fa3aa450aadb75d08e0c6ba88eb79b5ebaa449.1"]
    minimum_pre_commit_version: '0'
