-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.17.0-integration-engines-4-17-0-6-integration-views-ignore-bfe2c01ab9cc41683452116cbdac84a6031e2f6c.1"]
    minimum_pre_commit_version: '0'
