-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.11.0-integration-engines-4-11-0-44-feat-json-protocol-a39dfce7aaf451d19b106cc787d2ef2bd8be223e.1"]
    minimum_pre_commit_version: '0'
