-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.5.0-integration-engines-4-5-0-21-integration-remove-simulated-noaction-for-postgres-and-sqlite-2e08a7244ca876351adc7689a8c3551c315eac5c.1"]
    minimum_pre_commit_version: '0'
