-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.15.0-integration-engines-4-15-0-9-integration-engineer-tests-24ada487098a711c15bc172b9719694c9292f14f.1"]
    minimum_pre_commit_version: '0'
