-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.7.0-integration-engines-4-7-0-36-integration-closed-itx-error-message-f83defecb0b5e8d981b6553ff1dac315b1482bc4.1"]
    minimum_pre_commit_version: '0'
