-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.4.0-integration-engines-4-4-0-44-integration-database-assertion-violation-error-2-78d1421518fddc0b4cf781bcb17e2f3bca3b0f24.1"]
    minimum_pre_commit_version: '0'
