-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.2.0-integration-engines-4-2-0-14-query-engine-itx-isolation-1261b1df947d7ed71189ea4497d996e45522f3f6.1"]
    minimum_pre_commit_version: '0'
