-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.10.0-integration-engines-5-10-0-31-joins-distinct-1a693f2b982374446ba145038ac6bb6028481687.1"]
    minimum_pre_commit_version: '0'
