-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@2.26.0-integration-generator-cli-lookup.2"]
    minimum_pre_commit_version: '0'
