-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.16.0-integration-engines-4-16-0-65-integration-default-protocol-a001640fb1246b05489d399bc4d41dfd2c74f342.1"]
    minimum_pre_commit_version: '0'
