-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.6.0-integration-engines-5-6-0-31-integration-bump-mobc-d19bcc65cdabf1db98633bb5aa496b2bf2f6046d.2"]
    minimum_pre_commit_version: '0'
