-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.16.0-integration-engines-4-16-0-38-integration-node-drivers-typed-nonverbose-81afb6281350299d232ca0216ea77874926fb2a5.1"]
    minimum_pre_commit_version: '0'
