-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.12.0-integration-engines-4-12-0-45-integration-errors-jsonp-48093731ad366ed55019ccbc011a7c21d47a95a4.1"]
    minimum_pre_commit_version: '0'
