-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.6.0-integration-engines-5-6-0-17-integration-mff-517-18ad27daee2d562b8d75e34b5b30da2fc6a6ef17.1"]
    minimum_pre_commit_version: '0'
