-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.6.0-integration-engines-4-6-0-17-integration-native-upsert-4f20e7dfe38d443598aab36282b06d8145309714.1"]
    minimum_pre_commit_version: '0'
