-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.7.0-integration-engines-4-7-0-25-integration-update-napi-dep-3e5fff398fc149c544a2095ab46326314054a1d0.1"]
    minimum_pre_commit_version: '0'
