-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@3.7.0-integration-feat-tracing.6"]
    minimum_pre_commit_version: '0'
