-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.16.0-integration-engines-4-16-0-57-integration-linux-static-a156add034f679923521d232012267423a49deb3.1"]
    minimum_pre_commit_version: '0'
