-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.15.0-integration-fix-client-unclear-engine-not-found-messages.16"]
    minimum_pre_commit_version: '0'
