-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.7.0-integration-engines-5-7-0-13-driver-adapters-remove-dispose-method-for-js-transaction-interface-fc5d9935df947f2d7440701bc3eb8a5e93b039e5.1"]
    minimum_pre_commit_version: '0'
