-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.9.0-integration-engines-5-9-0-19-chore-update-napi-rs-to-latest-1ec47ad2e3265d5add9ceb21bb8a10b796d01c57.1"]
    minimum_pre_commit_version: '0'
