-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.11.0-integration-engines-4-11-0-37-feat-json-protocol-8b7b3b79041e8e5718f30b515ca81621bec59806.1"]
    minimum_pre_commit_version: '0'
