-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.4.0-integration-engines-4-4-0-25-integration-occ-fixes-8612-3589323e15f56a9d7f8ec753bbe124025ac1b452.1"]
    minimum_pre_commit_version: '0'
