-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.7.0-integration-engines-4-7-0-9-feat-error-req-idx-26e00ab332793084ea0280df387b126fb5e17eba.1"]
    minimum_pre_commit_version: '0'
