-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.10.0-integration-engines-4-10-0-23-integration-log-capture-prep-refactoring-5e8228ae65a1ca94f1055b14779cea9928cb6a12.1"]
    minimum_pre_commit_version: '0'
