-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@3.13.0-integration-fix-open-issues-on-windows.1"]
    minimum_pre_commit_version: '0'
