-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.16.0-integration-engines-4-16-0-69-integration-tracing-runtime-js-5640e37d36a967a91e3a56eaf0a8afbef0ffdcb8.1"]
    minimum_pre_commit_version: '0'
